### ISSUE TITLE
TypeError: type.getSymbol is not a function

### ISSUE THREAD

**Issue by Gorniaky** [nlepage/typedoc-plugin-resolve-crossmodule-references#17]
`TypeDoc 0.24.6`
`typedoc-plugin-resolve-crossmodule-references 0.3.3`

```sh
yarn run v1.22.19
$ typedoc
[info] Loaded plugin typedoc-plugin-resolve-crossmodule-references
[info] Converting project at ./packages/api-types
TypeDoc exiting with unexpected error:
TypeError: type.getSymbol is not a function
    at isReferenceTypeBroken (E:\_DisCloud\discloud.app\node_modules\typedoc-plugin-resolve-crossmodule-references\dist\index.js:149:44)
    at fixType (E:\_DisCloud\discloud.app\node_modules\typedoc-plugin-resolve-crossmodule-references\dist\index.js:104:34)        
    at fixTyped (E:\_DisCloud\discloud.app\node_modules\typedoc-plugin-resolve-crossmodule-references\dist\index.js:100:24)       
    at Object.conditional (E:\_DisCloud\discloud.app\node_modules\typedoc-plugin-resolve-crossmodule-references\dist\index.js:34:13)
    at Object.conditional (E:\_DisCloud\discloud.app\node_modules\typedoc\dist\lib\models\types.js:71:34)
    at ConditionalType.visit (E:\_DisCloud\discloud.app\node_modules\typedoc\dist\lib\models\types.js:42:36)
    at recursivelyFixTyped (E:\_DisCloud\discloud.app\node_modules\typedoc-plugin-resolve-crossmodule-references\dist\index.js:87:20)
    at visitReflection (E:\_DisCloud\discloud.app\node_modules\typedoc-plugin-resolve-crossmodule-references\dist\index.js:14:9)  
    at Converter.<anonymous> (E:\_DisCloud\discloud.app\node_modules\typedoc-plugin-resolve-crossmodule-references\dist\index.js:9:82)
    at triggerEvents (E:\_DisCloud\discloud.app\node_modules\typedoc\dist\lib\utils\events.js:196:43)
error Command failed with exit code 6.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by nlepage** [comment]
According to https://github.com/TypeStrong/typedoc/issues/1835#issuecomment-1500991906 this plugin isn't necessary anymore if you have typedoc v0.24 or greater.
I will update the Readme soon in order to mention this.

**Comment by Gorniaky** [comment]
@nlepage 

Oh! Thanks for the info.
